version: 3.0.{build}
branches:
  only:
  - master
  - /release\/.*/
skip_tags: true
cache:
- C:\Users\appveyor\.gradle\wrapper -> gradle\wrapper\gradle-wrapper.properties
- C:\Users\appveyor\.gradle\caches
environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.7.0
init:
- path C:\Miniconda-x64;C:\Miniconda-x64\Scripts;%PATH%
# update Conda so we have the right version for later
- conda update -q -y conda
install:
- conda env create -q -f etc\environment.yml
- activate lenskit
- gradlew.bat ciPrep
build_script:
- gradlew.bat ciBuild
test_script:
- gradlew.bat check -Pjavadoc.skip=true
deploy: off
